### ISSUE TITLE
Consider using mailto links for team page

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/leafwing-website#138]
You can use `mailto:` links on email addresses, then clicking them will open your email software to compose a new email to this address ([MDN docs](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#e-mail_links)).

I assume that this also makes it easier for bots to scrape the emails, so this could be a potential downside.

**Comment by alice-i-cecile** [comment]
Yeah, I was chewing on this. My feeling is that bots can scrape it trivially anyways, might as well make this nice.
