### ISSUE TITLE
Typos on "Projects" page

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/leafwing-website#165]
In the section "Open Source Contributions":

> If you love our [open source tools](https://github.com/leafwing-studios/), consider funding this work us on [GitHub Sponsors](hhttps://github.com/sponsors/alice-i-cecile).

Should be either "this work" or "us", not both.

Also, the GitHub Sponsors link is broken ("hhttps" instead of "https").

**Comment by alice-i-cecile** [comment]
Thank you!
