### ISSUE TITLE
RSS feed gives 404 error

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/leafwing-website#167]
Opening the RSS feed gives a 404 error:
<https://www.leafwing-studios.com/rss.xml>

**Comment by alice-i-cecile** [comment]
Oof, thank you.

**Comment by alice-i-cecile** [comment]
This *was* working previously. I think that the problem here is that the set of blog posts is empty.

**Comment by TimJentzsch** [comment]
Yeah, I think it previously worked for me too (otherwise I'd probably have created an issue earlier :wink:)
