### ISSUE TITLE
Contrast of header colors too low

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/leafwing-website#175]
## What's wrong?

The header uses `#97d968` on `#39661a`, which doesn't pass WCAG AAA standards for large text:
![Contrast analysis for the header colors](https://user-images.githubusercontent.com/13908946/180498894-cb8912c8-bbba-4d47-be65-cca091ac274d.png)

A bigger problem is the hover color of the nav links in the header (`#5ca329`). That does also not pass the AA standards for contrast.

I assume that you don't want to change the logo color, so the best option would be to make the background darker.

- `#2e5215` would be the next best green that passes AAA for large text, but not for the hover.
- `#223d10` would be the next best green that passes AAA for small text, but not for the hover.
- `#1b300d` also works for AAA large text with the hover color, but it's quite the dark green.

    ![Preview of the dark green as header color](https://user-images.githubusercontent.com/13908946/180500877-c5754c7a-0c38-4a85-a373-7ace249e7360.png)

**Other options**:

- `#252525` would has good contrast with the primary and hover color (but maybe a bit bland)?

    ![Preview of the dark gray as header color](https://user-images.githubusercontent.com/13908946/180500260-c2a9d5e5-1735-4f66-8bdb-7dede1465b8b.png)

- `#421f00` would also work well with both colors, but introduces an additional color hue to think about.
  
    ![Preview of the dark brown as header color](https://user-images.githubusercontent.com/13908946/180500139-b2df271a-bb28-41e6-9e48-a02d0d2e80c3.png)

**Comment by alice-i-cecile** [comment]
![image](https://user-images.githubusercontent.com/3579909/180506115-4dc9384c-56cd-49d3-b981-85ffa9c95851.png)

Leaning towards very dark green.
